#!/bin/bash
#
# Short bash script for running fully bundled release
# which includes the required JVM and JRuby component
# Set TELEGARD_HOME to the installation prefix.
 
TELEGARD_HOME=/opt/telegard


##### DO NOT CHANGE BELOW THIS LINE #####
#

# Uncomment to use Sun Java in contrib.
#JAVA_HOME=$TELEGARD_HOME/contrib/jdk
#$JAVA_HOME/bin/java -version

# JRuby
JRUBY_HOME=$TELEGARD_HOME/contrib/jruby

java -version
cd $TELEGARD_HOME/bbs

trap "echo false" SIGSTOP
$JRUBY_HOME/bin/jruby -W0 -I bbs/lib tg.rb $*
#$JRUBY_HOME/bin/jirb

#
#########################################
